version: "3"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  api:
    build:
      context: .
      dockerfile: ${PWD}/build/python/Dockerfile
    volumes:
      - .:/home/user/app
      - pip_volume:/home/user/.local/lib/python3.10/site-packages
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}

volumes:
  postgres_volume:
  pip_volume:
